"""Non-human / replay detection. OWNER: Agent B (bot).

A separate signal, never folded into the behaviour score: a bot is not "an
unusual owner", it is a different kind of fraud and gets its own reasons.

STUB: only the cheapest hard rules. Agent B replaces it.
"""

from __future__ import annotations

from contracts import FeatureVector, Sample, SignalResult


def check(
    sample: Sample,
    vector: FeatureVector | None,
    prior_vectors: list[list[float]],
    password_length: int,
) -> SignalResult:
    """`vector` is this attempt's keystroke vector (None if unscorable);
    `prior_vectors` are this user's stored vectors, for replay detection;
    `password_length` is len(password) of the (correct) password submitted, so a
    script that sets the field's value without typing is caught."""
    reasons: list[str] = []
    if any(not e.trusted for e in sample.keystrokes):
        reasons.append("key events were generated by a script (isTrusted=false)")
    if sample.env.get("webdriver"):
        reasons.append("browser reports it is automated (navigator.webdriver)")
    return SignalResult(name="bot", score=float(len(reasons)), threshold=0.5, flagged=bool(reasons), reasons=reasons)
